#!/usr/bin/env python

from flask.ext.script import Manager, Server
from flask.ext.assets import ManageAssets

from cabin import create_app

manager = Manager(create_app)
manager.add_command('assets', ManageAssets())
manager.add_command('runserver', Server(host='0.0.0.0', port=5002))


if __name__ == "__main__":
    manager.run()
