#!/usr/bin/env python

import subprocess

from flask.ext.script import Manager, Server
from flask.ext.assets import ManageAssets

from cabin import create_app, models, redis

manager = Manager(create_app)
manager.add_command('assets', ManageAssets())
manager.add_command('runserver', Server(host='0.0.0.0', port=5002))

@manager.shell
def make_shell_context():
    return dict(r=redis, models=models)

@manager.command
def test():
    """Run the tests."""
    subprocess.call('py.test')


if __name__ == "__main__":
    manager.run()
